[package]
name = "Morrowind MCP Server"
description = "MCP server for reading Morrowind game state and metadata, and performing in-game actions."
homepage = "placeholder"
repository = "https://github.com/longod/morrowind-mcp"
authors = ["longod"]
version = "0.0.0"

[dependencies.mwse]
buildnumber = 5103

[dependencies.mge-xe]
version = ">=0.15.0"
