local this = {}
local enumname = require("morrowind-mcp.tes3.enumname")
local logger = require("morrowind-mcp.logger").Get({ moduleName = "ui_action" })

local defaultPathSeparator = "|"

-- Native Morrowind menus can attach meaningful handlers to widgetless layout elements.
-- Only keep properties that are plausible direct input actions for menu-action style triggering.
local actionableProperty = {
    [tes3.uiProperty.mouseClick] = true,
    [tes3.uiProperty.doubleClick] = true,
    [tes3.uiProperty.release] = true,
    [tes3.uiProperty.keyPress] = true,
    [tes3.uiProperty.enter] = true,
}

-- Static hints cover vanilla/native elements that are known to be actionable before they are observed.
-- Rows generated by FormatObservedHintsForStaticList can be promoted here after manual review.
---@type MCP.UIActionHint[]
local staticHints = {
    {
        path = "layout|MenuBook|PartNonDragMenu_main|null|MenuBook_buttons_left|null|MenuBook_button_prev",
        properties = { "mouseClick" },
        name = "MenuBook_button_prev"
    },
    {
        path = "layout|MenuBook|PartNonDragMenu_main|null|MenuBook_buttons_left|null|MenuBook_button_take",
        properties = { "mouseClick" },
        name = "MenuBook_button_take"
    },
    {
        path = "layout|MenuBook|PartNonDragMenu_main|null|MenuBook_buttons_right|null|MenuBook_button_close",
        properties = { "mouseClick", "keyPress" },
        name = "MenuBook_button_close"
    },
    {
        path = "layout|MenuBook|PartNonDragMenu_main|null|MenuBook_buttons_right|null|MenuBook_button_next",
        properties = { "mouseClick" },
        name = "MenuBook_button_next"
    },
    {
        path = "layout|MenuJournal|PartNonDragMenu_main|MenuJournal_bookmark|MenuJournal_button_bookmark_cancel",
        properties = { "mouseClick" },
        name = "MenuJournal_button_bookmark_cancel"
    },
    {
        path = "layout|MenuJournal|PartNonDragMenu_main|MenuJournal_bookmark|null|MenuJournal_button_bookmark_quests",
        properties = { "mouseClick" },
        name = "MenuJournal_button_bookmark_quests"
    },
    {
        path = "layout|MenuJournal|PartNonDragMenu_main|MenuJournal_bookmark|null|MenuJournal_button_bookmark_topics",
        properties = { "mouseClick" },
        name = "MenuJournal_button_bookmark_topics"
    },
    {
        path = "layout|MenuJournal|PartNonDragMenu_main|null|MenuBook_buttons_left|null|MenuBook_button_take",
        properties = { "mouseClick" },
        name = "MenuBook_button_take"
    },
    {
        path = "layout|MenuJournal|PartNonDragMenu_main|null|MenuBook_buttons_right|null|MenuBook_button_close",
        properties = { "mouseClick" },
        name = "MenuBook_button_close"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|MenuOptions_Exit_container",
        properties = { "mouseClick" },
        name = "MenuOptions_Exit_container"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|MenuOptions_Load_container",
        properties = { "mouseClick" },
        name = "MenuOptions_Load_container"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|MenuOptions_MCM_container",
        properties = { "mouseClick" },
        name = "MenuOptions_MCM_container"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|MenuOptions_New_container",
        properties = { "mouseClick" },
        name = "MenuOptions_New_container"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|MenuOptions_Options_container",
        properties = { "mouseClick" },
        name = "MenuOptions_Options_container"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|MenuOptions_Return_container",
        properties = { "mouseClick" },
        name = "MenuOptions_Return_container"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|MenuOptions_Save_container",
        properties = { "mouseClick" },
        name = "MenuOptions_Save_container"
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|ImprovedMainMenu:ContinueButton",
        properties = { "mouseClick" },
        name = "ImprovedMainMenu:ContinueButton" -- Improved Main Menu mod
    },
    {
        path = "layout|MenuOptions|PartNonDragMenu_main|null|Pete_ContinueButton",
        properties = { "mouseClick" },
        name = "Pete_ContinueButton" -- Continue mod
    },
    {
        path = "layout|MenuScroll|PartNonDragMenu_main|null|MenuBook_PickupButton",
        properties = { "mouseClick" },
        name = "MenuBook_PickupButton"
    },
    {
        path = "layout|MenuScroll|PartNonDragMenu_main|null|MenuScroll_Close",
        properties = { "mouseClick" },
        name = "MenuScroll_Close"
    },

}

---@class MCP.UIActionHint
---@field path string
---@field properties string[] -- tes3.uiProperty names
---@field observed boolean?
---@field name string?

-- Runtime observations override static hints because they reflect the currently loaded UI tree.
---@type table<string, MCP.UIActionHint>
local observedHintByPath = {}
local observedHintsDirty = false


---@type table<string, MCP.UIActionHint>
local staticHintByPath = {}

-- Build an index once at module load so serialization can do constant-time lookups by path.
for _, hint in ipairs(staticHints) do
    if staticHintByPath[hint.path] then
        logger:error("Duplicate static UI action hint path=%s", hint.path)
    end
    staticHintByPath[hint.path] = hint
end

-- Prefer names because they are the most stable human-readable UI identity.
-- Fall back to type so unnamed structural ancestors can still participate in the path.
---@param element tes3uiElement
---@return string?
local function GetPathSegment(element)
    if type(element.name) == "string" and element.name ~= "" then
        return element.name
    end
    if type(element.type) == "string" and element.type ~= "" then
        return element.type
    end
    logger:warn("Failed to build UI action path segment because element has neither name nor type")
    return nil
end

--- Builds a stable UI path for matching native layout events, not a filesystem or resource path.
---@param element tes3uiElement
---@param separator string?
---@return string?
function this.BuildElementPath(element, separator)
    if not element then
        return nil
    end

    local pathSeparator = separator or defaultPathSeparator
    local segments = {}
    local current = element
    while current do
        -- A missing segment means the path cannot be safely promoted to a static hint.
        local segment = GetPathSegment(current)
        if not segment then
            return nil
        end
        table.insert(segments, 1, segment)
        current = current.parent
    end

    return table.concat(segments, pathSeparator)
end

--- Checks element validity defensively because observed UI objects may disappear between events.
---@param element tes3uiElement
---@return boolean
local function IsValidElement(element)
    if not element then
        return false
    end
    if type(element.isValid) ~= "function" then
        return false
    end

    local ok, valid = pcall(function()
        return element:isValid()
    end)
    return ok and valid == true
end

--- Limits this helper to the native layout case that widgets do not already describe.
---@param element tes3uiElement
---@return boolean
local function IsCollectableElement(element)
    if not IsValidElement(element) then
        return false
    end
    if element.widget ~= nil then
        return false
    end
    return element.type == "layout"
end

--- Filters before enum-name conversion to avoid retaining hover/state-change noise from uiPreEvent.
---@param property tes3.uiProperty
---@return boolean
local function IsActionableProperty(property)
    return actionableProperty[property] == true
end

--- Adds one property name while preserving first-observed order and avoiding duplicate output.
---@param properties string[]
---@param property string
---@return boolean added
local function AddProperty(properties, property)
    for _, existingProperty in ipairs(properties) do
        if existingProperty == property then
            return false
        end
    end
    table.insert(properties, property)
    return true
end

--- Records a uiPreEvent source element when it is a widgetless layout native action candidate.
--- Observations are intentionally passive; they do not claim or trigger UI events.
---@param e uiPreEventEventData
function this.ObserveUiPreEvent(e)
    local source = e and e.source
    if not IsCollectableElement(source) then
        return nil
    end

    if not IsActionableProperty(e.property) then
        return nil
    end

    -- Path matching is delayed until after property filtering because uiPreEvent is high-volume.
    local path = this.BuildElementPath(source)
    if not path then
        logger:warn("Skipped UI action observation because path could not be built")
        return nil
    end

    local property = enumname.uiProperty(e.property)
    if not property then
        logger:warn("Skipped UI action observation because actionable uiProperty is unknown: %s", tostring(e.property))
        return nil
    end

    local hint = observedHintByPath[path]
    if not hint then
        -- Store only promotion and lookup data; the serializer already includes element name/type.
        hint = {
            path = path,
            properties = {},
            observed = true,
            name = source.name,
        }
        observedHintByPath[path] = hint
    end

    local added = AddProperty(hint.properties, property)
    if added and table.size(hint.properties) == 1 then
        observedHintsDirty = true
        logger:debug("Observed UI action hint path=%s property=%s name=%s type=%s", path, property, tostring(source.name),
            tostring(source.type))
    elseif added then
        observedHintsDirty = true
        logger:trace("Added observed UI action hint property path=%s property=%s", path, property)
    end
end

--- Logs the current promotion dump once a menu interaction batch has finished.
---@param e menuExitEventData
local function OnMenuExit(e)
    if not observedHintsDirty then
        return
    end

    local config = require("morrowind-mcp.config")
    if not config.development.debug then
        return
    end

    local dump = this.FormatObservedHintsForStaticList()
    if dump == "" then
        return
    end

    logger:debug("Observed UI action hints for static list:\n%s", dump)
    observedHintsDirty = false
end

--- Registers passive uiPreEvent observation during runtime startup.
function this.RegisterEventHandlers()
    event.register(tes3.event.uiPreEvent, this.ObserveUiPreEvent)
    event.register(tes3.event.menuExit, OnMenuExit)
    logger:debug("UI action observation event handler registered")
end

--- Returns the observed or static executable event hint for an element.
---@param element tes3uiElement
---@return MCP.UIActionHint?
local function GetActionHint(element)
    if not IsCollectableElement(element) then
        return nil
    end

    local path = this.BuildElementPath(element)
    if not path then
        return nil
    end

    -- Runtime observations win over static hints so modded or stateful menus can refine defaults.
    local observedHint = observedHintByPath[path]
    if observedHint then
        return observedHint
    end

    local staticHint = staticHintByPath[path]
    if staticHint then
        return staticHint
    end

    return nil
end

--- Returns only the event properties needed by serialized UI output.
--- The path/name metadata stays internal because the serializer already emits element identity.
---@param element tes3uiElement
---@return string[]? properties tes3.uiProperty names
function this.GetActionProperties(element)
    local hint = GetActionHint(element)
    return hint and hint.properties or nil
end

--- Clears runtime-observed hints so tests do not leak fake UI data into normal play.
function this.ClearObservedHints()
    observedHintByPath = {}
    observedHintsDirty = false
end

--- Quotes a Lua string literal for static hint dump output.
---@param value string
---@return string
local function LuaQuote(value)
    return string.format("%q", value)
end

--- Formats one hint as a staticHints row for copy/paste promotion.
---@param hint MCP.UIActionHint
---@return string
local function FormatStaticHintRow(hint)
    local propertyLiterals = {}
    for _, property in ipairs(hint.properties) do
        table.insert(propertyLiterals, LuaQuote(property))
    end

    local parts = {
        "{ path = " .. LuaQuote(hint.path),
        "properties = { " .. table.concat(propertyLiterals, ", ") .. " }",
    }
    if hint.name then
        table.insert(parts, "name = " .. LuaQuote(hint.name))
    end
    return "    " .. table.concat(parts, ", ") .. " },"
end

--- Formats observed hints as Lua table rows that can be promoted into the static list.
--- The dump intentionally omits runtime IDs and observed markers because static hints must be stable.
---@return string
function this.FormatObservedHintsForStaticList()
    local keys = {}
    for key in pairs(observedHintByPath) do
        table.insert(keys, key)
    end
    table.sort(keys)

    local lines = {}
    for _, key in ipairs(keys) do
        table.insert(lines, FormatStaticHintRow(observedHintByPath[key]))
    end
    return table.concat(lines, "\n")
end

--- Changes the path separator for tests or future compatibility with different path encodings.
---@param separator string
function this.SetDefaultPathSeparator(separator)
    if type(separator) ~= "string" or separator == "" then
        logger:error("Invalid UI action path separator: %s", tostring(separator))
        return
    end
    defaultPathSeparator = separator
end

return this
